[package]
name = "aoc21"
version = "0.1.0"
authors = ["Chris Jordan <chris.jordan@news.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
